# Generated by Django 3.2.5 on 2021-07-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210723_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='fonte',
        ),
    ]
