# Generated by Django 3.2.5 on 2021-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postagem_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='fonte',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
